export const skillsDatas = [
  {
    id: 1,
    src: "/logos/css-logo.svg",
    alt: "CSS Logo",
    title: "CSS",
    type: "languages",
  },
  {
    id: 2,
    src: "/logos/js-logo.svg",
    alt: "JavaScript Logo",
    title: "JavaScript",
    type: "languages",
  },
  {
    id: 3,
    src: "/logos/ts-logo.svg",
    alt: "TS Logo",
    title: "TypeScript",
    type: "languages",
  },
  {
    id: 5,
    src: "/logos/php-logo.svg",
    alt: "PHP Logo",
    title: "PHP",
    type: "languages",
  },
  {
    id: 6,
    src: "/logos/sql-logo.svg",
    alt: "SQL Logo",
    title: "SQL",
    type: "languages",
  },
  {
    id: 7,
    src: "/logos/docker-logo.svg",
    alt: "Docker Logo",
    title: "",
    type: "applications",
  },
  {
    id: 8,
    src: "/logos/github-logo.svg",
    alt: "GitHub Logo",
    title: "GitHub",
    type: "applications",
  },
  {
    id: 9,
    src: "/logos/mariadb-logo.svg",
    alt: "MariaDB Logo",
    title: "MariaDB",
    type: "applications",
  },
  {
    id: 10,
    src: "/logos/postresql-logo.svg",
    alt: "PostgreSQL Logo",
    title: "PostgreSQL",
    type: "applications",
  },
  {
    id: 11,
    src: "/logos/tailwind-logo.svg",
    alt: "Tailwind CSS Logo",
    title: "Tailwind CSS",
    type: "frameworks",
  },
  {
    id: 12,
    src: "/logos/react-logo.svg",
    alt: "React Logo",
    title: "React",
    type: "frameworks",
  },
  {
    id: 13,
    src: "/logos/next-logo.svg",
    alt: "Next.js Logo",
    title: "Next.js",
    type: "frameworks",
  },
  {
    id: 14,
    src: "/logos/gin-logo.svg",
    alt: "Gin Logo",
    title: "Gin",
    type: "frameworks",
  },
  {
    id: 15,
    src: "/logos/symfony-logo.svg",
    alt: "Symfony Logo",
    title: "Symfony",
    type: "frameworks",
  },
];
