import type { Metadata } from "next";
import "./globals.css";
import MainMenu from "@/components/organisms/MainMenu";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="font-sans ">
      <body className="mx-auto flex min-h-screen max-w-4xl flex-col ">
        <main className="grow md:px-8 px-2">
          <MainMenu />

          {children}
        </main>
        <footer className="my-6 flex gap-6 flex-wrap items-center justify-center">
          <section>
            <p className="text-center text-xs text-muted-foreground">
              <span>© 2024 </span>
              <Link className="link" href="/">
                portfolio.thibault-rossa.fr
              </Link>
              {" | "}
              <a className="link font-bold" href="/privacy">
                privacy?
              </a>
            </p>
          </section>
        </footer>
      </body>
    </html>
  );
}
